### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by Shuimo03**
## Kats

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/facebookresearch/Kats/blob/main/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

- [x] Fork the repo and create your branch from `main`.
- [ ] If you've added code that should be tested, add tests.
- [ ] If you've changed APIs, update the documentation.
- [x] Ensure the test suite passes.
- [x] Make sure your code lints.
- [x] If you haven't already, complete the Contributor License Agreement ("CLA").

Contributor License Agreement ("CLA")
In order to accept your pull request, we need you to submit a CLA. You only need to do this once to work on any of Facebook's open source projects.

Complete your CLA here: https://code.facebook.com/cla

`Ver: Kats v1.02`

### CODE REVIEW

**Comment by irumata** [comment]
hi!
Thanks for contributing, can you explain how it helps to fix the issue?

**Comment by Shuimo03** [comment]
yes, The issues mainly because many we have different environments, kats requires python3.7 but many people maybe be higher than this version. So I provide a Dockerfile which can slove the problem of environment consistency, to be able to quickly experience the kats

**Comment by Shuimo03** [comment]
yes, The issues mainly because many we have different environments, kats requires python3.7 but many people maybe be higher than this version. So I provide a Dockerfile which can slove the problem of environment consistency, to be able to quickly experience the kats

**Comment by benzid-wael** [comment]
Hi @Shuimo03 

Thanks for taking the time to create this diff

I don't see the value of adding dockerfile here.

If kats is broken for specific version, please create an issue and appreciate if you add a PR to fix it as well, does it make sense?

**Pull request closed without merging**
